/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditActionSummary
 */
export interface AuditActionSummary {
    /**
     * 
     * @type {string}
     * @memberof AuditActionSummary
     */
    action: string;
    /**
     * 
     * @type {number}
     * @memberof AuditActionSummary
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof AuditActionSummary
     */
    failure: number;
    /**
     * 
     * @type {number}
     * @memberof AuditActionSummary
     */
    success: number;
    /**
     * 
     * @type {number}
     * @memberof AuditActionSummary
     */
    successRatePercent: number;
}

/**
 * Check if a given object implements the AuditActionSummary interface.
 */
export function instanceOfAuditActionSummary(value: object): value is AuditActionSummary {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('failure' in value) || value['failure'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('successRatePercent' in value) || value['successRatePercent'] === undefined) return false;
    return true;
}

export function AuditActionSummaryFromJSON(json: any): AuditActionSummary {
    return AuditActionSummaryFromJSONTyped(json, false);
}

export function AuditActionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditActionSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'count': json['count'],
        'failure': json['failure'],
        'success': json['success'],
        'successRatePercent': json['success_rate_percent'],
    };
}

export function AuditActionSummaryToJSON(json: any): AuditActionSummary {
    return AuditActionSummaryToJSONTyped(json, false);
}

export function AuditActionSummaryToJSONTyped(value?: AuditActionSummary | null, ignoreDiscriminator = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'count': value['count'],
        'failure': value['failure'],
        'success': value['success'],
        'success_rate_percent': value['successRatePercent'],
    };
}

