/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkWebhookOperationRequest
 */
export interface BulkWebhookOperationRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof BulkWebhookOperationRequest
     */
    readonly $schema?: string;
    /**
     * Operation (activate, deactivate, delete)
     * @type {string}
     * @memberof BulkWebhookOperationRequest
     */
    operation: string;
    /**
     * Reason for operation
     * @type {string}
     * @memberof BulkWebhookOperationRequest
     */
    reason?: string;
    /**
     * Webhook IDs
     * @type {Array<string>}
     * @memberof BulkWebhookOperationRequest
     */
    webhookIds: Array<string> | null;
}

/**
 * Check if a given object implements the BulkWebhookOperationRequest interface.
 */
export function instanceOfBulkWebhookOperationRequest(value: object): value is BulkWebhookOperationRequest {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('webhookIds' in value) || value['webhookIds'] === undefined) return false;
    return true;
}

export function BulkWebhookOperationRequestFromJSON(json: any): BulkWebhookOperationRequest {
    return BulkWebhookOperationRequestFromJSONTyped(json, false);
}

export function BulkWebhookOperationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkWebhookOperationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'operation': json['operation'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'webhookIds': json['webhookIds'] == null ? null : json['webhookIds'],
    };
}

export function BulkWebhookOperationRequestToJSON(json: any): BulkWebhookOperationRequest {
    return BulkWebhookOperationRequestToJSONTyped(json, false);
}

export function BulkWebhookOperationRequestToJSONTyped(value?: Omit<BulkWebhookOperationRequest, '$schema'> | null, ignoreDiscriminator = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'reason': value['reason'],
        'webhookIds': value['webhookIds'],
    };
}

