/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgType } from './OrgType';
import {
    OrgTypeFromJSON,
    OrgTypeFromJSONTyped,
    OrgTypeToJSON,
    OrgTypeToJSONTyped,
} from './OrgType';

/**
 * 
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    [key: string]: any | any;
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    readonly $schema?: string;
    /**
     * Auth service configuration
     * @type {object}
     * @memberof CreateOrganizationRequest
     */
    authConfig?: object;
    /**
     * Whether to create trial period
     * @type {boolean}
     * @memberof CreateOrganizationRequest
     */
    createTrialPeriod: boolean;
    /**
     * Primary domain
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    domain?: string;
    /**
     * Enable auth service
     * @type {boolean}
     * @memberof CreateOrganizationRequest
     */
    enableAuthService: boolean;
    /**
     * End user limit
     * @type {number}
     * @memberof CreateOrganizationRequest
     */
    endUserLimit: number;
    /**
     * External user limit
     * @type {number}
     * @memberof CreateOrganizationRequest
     */
    externalUserLimit: number;
    /**
     * Logo URL
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    logoUrl?: string;
    /**
     * Additional metadata
     * @type {object}
     * @memberof CreateOrganizationRequest
     */
    metadata?: object;
    /**
     * Organization name
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    name: string;
    /**
     * Organization type
     * @type {OrgType}
     * @memberof CreateOrganizationRequest
     */
    orgType: OrgType;
    /**
     * Owner email (will create user if not exists)
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    ownerEmail?: string;
    /**
     * Initial subscription plan
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    plan: string;
    /**
     * Unique slug (auto-generated if not provided)
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    slug?: string;
}



/**
 * Check if a given object implements the CreateOrganizationRequest interface.
 */
export function instanceOfCreateOrganizationRequest(value: object): value is CreateOrganizationRequest {
    if (!('createTrialPeriod' in value) || value['createTrialPeriod'] === undefined) return false;
    if (!('enableAuthService' in value) || value['enableAuthService'] === undefined) return false;
    if (!('endUserLimit' in value) || value['endUserLimit'] === undefined) return false;
    if (!('externalUserLimit' in value) || value['externalUserLimit'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('orgType' in value) || value['orgType'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    return true;
}

export function CreateOrganizationRequestFromJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'authConfig': json['authConfig'] == null ? undefined : json['authConfig'],
        'createTrialPeriod': json['createTrialPeriod'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'enableAuthService': json['enableAuthService'],
        'endUserLimit': json['endUserLimit'],
        'externalUserLimit': json['externalUserLimit'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'orgType': OrgTypeFromJSON(json['orgType']),
        'ownerEmail': json['ownerEmail'] == null ? undefined : json['ownerEmail'],
        'plan': json['plan'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function CreateOrganizationRequestToJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestToJSONTyped(json, false);
}

export function CreateOrganizationRequestToJSONTyped(value?: Omit<CreateOrganizationRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'authConfig': value['authConfig'],
        'createTrialPeriod': value['createTrialPeriod'],
        'domain': value['domain'],
        'enableAuthService': value['enableAuthService'],
        'endUserLimit': value['endUserLimit'],
        'externalUserLimit': value['externalUserLimit'],
        'logoUrl': value['logoUrl'],
        'metadata': value['metadata'],
        'name': value['name'],
        'orgType': OrgTypeToJSON(value['orgType']),
        'ownerEmail': value['ownerEmail'],
        'plan': value['plan'],
        'slug': value['slug'],
    };
}

