/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { UserActivity } from './UserActivity';
import {
    UserActivityFromJSON,
    UserActivityFromJSONTyped,
    UserActivityToJSON,
    UserActivityToJSONTyped,
} from './UserActivity';

/**
 * 
 * @export
 * @interface PaginatedOutputUserActivity
 */
export interface PaginatedOutputUserActivity {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PaginatedOutputUserActivity
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<UserActivity>}
     * @memberof PaginatedOutputUserActivity
     */
    data: Array<UserActivity> | null;
    /**
     * 
     * @type {Pagination}
     * @memberof PaginatedOutputUserActivity
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the PaginatedOutputUserActivity interface.
 */
export function instanceOfPaginatedOutputUserActivity(value: object): value is PaginatedOutputUserActivity {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedOutputUserActivityFromJSON(json: any): PaginatedOutputUserActivity {
    return PaginatedOutputUserActivityFromJSONTyped(json, false);
}

export function PaginatedOutputUserActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedOutputUserActivity {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(UserActivityFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function PaginatedOutputUserActivityToJSON(json: any): PaginatedOutputUserActivity {
    return PaginatedOutputUserActivityToJSONTyped(json, false);
}

export function PaginatedOutputUserActivityToJSONTyped(value?: Omit<PaginatedOutputUserActivity, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(UserActivityToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

