/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetConfirmRequest
 */
export interface PasswordResetConfirmRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    readonly $schema?: string;
    /**
     * New password
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    newPassword: string;
    /**
     * Password reset token
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    token: string;
}

export function PasswordResetConfirmRequestFromJSON(json: any): PasswordResetConfirmRequest {
    return PasswordResetConfirmRequestFromJSONTyped(json, false);
}

export function PasswordResetConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetConfirmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '$schema': !exists(json, '$schema') ? undefined : json['$schema'],
        'newPassword': json['newPassword'],
        'token': json['token'],
    };
}

export function PasswordResetConfirmRequestToJSON(value?: PasswordResetConfirmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newPassword': value.newPassword,
        'token': value.token,
    };
}


