/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { PlatformUserSummary } from './PlatformUserSummary';
import {
    PlatformUserSummaryFromJSON,
    PlatformUserSummaryFromJSONTyped,
    PlatformUserSummaryToJSON,
    PlatformUserSummaryToJSONTyped,
} from './PlatformUserSummary';
import type { UserSummaryStats } from './UserSummaryStats';
import {
    UserSummaryStatsFromJSON,
    UserSummaryStatsFromJSONTyped,
    UserSummaryStatsToJSON,
    UserSummaryStatsToJSONTyped,
} from './UserSummaryStats';

/**
 * 
 * @export
 * @interface PlatformUserListResponse
 */
export interface PlatformUserListResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PlatformUserListResponse
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Pagination}
     * @memberof PlatformUserListResponse
     */
    pagination: Pagination;
    /**
     * 
     * @type {UserSummaryStats}
     * @memberof PlatformUserListResponse
     */
    summary: UserSummaryStats;
    /**
     * 
     * @type {Array<PlatformUserSummary>}
     * @memberof PlatformUserListResponse
     */
    users: Array<PlatformUserSummary> | null;
}

/**
 * Check if a given object implements the PlatformUserListResponse interface.
 */
export function instanceOfPlatformUserListResponse(value: object): value is PlatformUserListResponse {
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function PlatformUserListResponseFromJSON(json: any): PlatformUserListResponse {
    return PlatformUserListResponseFromJSONTyped(json, false);
}

export function PlatformUserListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformUserListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'pagination': PaginationFromJSON(json['pagination']),
        'summary': UserSummaryStatsFromJSON(json['summary']),
        'users': (json['users'] == null ? null : (json['users'] as Array<any>).map(PlatformUserSummaryFromJSON)),
    };
}

export function PlatformUserListResponseToJSON(json: any): PlatformUserListResponse {
    return PlatformUserListResponseToJSONTyped(json, false);
}

export function PlatformUserListResponseToJSONTyped(value?: Omit<PlatformUserListResponse, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': PaginationToJSON(value['pagination']),
        'summary': UserSummaryStatsToJSON(value['summary']),
        'users': (value['users'] == null ? null : (value['users'] as Array<any>).map(PlatformUserSummaryToJSON)),
    };
}

