/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendVerificationResponse
 */
export interface ResendVerificationResponse {
    [key: string]: any | any;
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ResendVerificationResponse
     */
    readonly $schema?: string;
    /**
     * Available verification methods
     * @type {Array<string>}
     * @memberof ResendVerificationResponse
     */
    availableMethods?: Array<string>;
    /**
     * Response message
     * @type {string}
     * @memberof ResendVerificationResponse
     */
    message: string;
    /**
     * When next attempt is allowed
     * @type {Date}
     * @memberof ResendVerificationResponse
     */
    nextAttemptAt?: Date;
    /**
     * Remaining verification attempts
     * @type {number}
     * @memberof ResendVerificationResponse
     */
    rateLimitRemaining?: number;
    /**
     * Whether verification was resent
     * @type {boolean}
     * @memberof ResendVerificationResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the ResendVerificationResponse interface.
 */
export function instanceOfResendVerificationResponse(value: object): value is ResendVerificationResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ResendVerificationResponseFromJSON(json: any): ResendVerificationResponse {
    return ResendVerificationResponseFromJSONTyped(json, false);
}

export function ResendVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'availableMethods': json['availableMethods'] == null ? undefined : json['availableMethods'],
        'message': json['message'],
        'nextAttemptAt': json['nextAttemptAt'] == null ? undefined : (new Date(json['nextAttemptAt'])),
        'rateLimitRemaining': json['rateLimitRemaining'] == null ? undefined : json['rateLimitRemaining'],
        'success': json['success'],
    };
}

export function ResendVerificationResponseToJSON(json: any): ResendVerificationResponse {
    return ResendVerificationResponseToJSONTyped(json, false);
}

export function ResendVerificationResponseToJSONTyped(value?: Omit<ResendVerificationResponse, '$schema'> | null, ignoreDiscriminator = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'availableMethods': value['availableMethods'],
        'message': value['message'],
        'nextAttemptAt': value['nextAttemptAt'] == null ? undefined : ((value['nextAttemptAt']).toISOString()),
        'rateLimitRemaining': value['rateLimitRemaining'],
        'success': value['success'],
    };
}

