/* tslint:disable */
/* eslint-disable */
/**
 * Frank Authentication API
 * Multi-tenant authentication SaaS platform API with Clerk.js compatibility
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@frankauth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityOverview
 */
export interface SecurityOverview {
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    activeThreats: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    compromisedAccounts: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    failedLogins: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    resolvedThreats: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    securityScore: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    suspiciousActivity: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityOverview
     */
    vulnerabilities: number;
}

/**
 * Check if a given object implements the SecurityOverview interface.
 */
export function instanceOfSecurityOverview(value: object): value is SecurityOverview {
    if (!('activeThreats' in value) || value['activeThreats'] === undefined) return false;
    if (!('compromisedAccounts' in value) || value['compromisedAccounts'] === undefined) return false;
    if (!('failedLogins' in value) || value['failedLogins'] === undefined) return false;
    if (!('resolvedThreats' in value) || value['resolvedThreats'] === undefined) return false;
    if (!('securityScore' in value) || value['securityScore'] === undefined) return false;
    if (!('suspiciousActivity' in value) || value['suspiciousActivity'] === undefined) return false;
    if (!('vulnerabilities' in value) || value['vulnerabilities'] === undefined) return false;
    return true;
}

export function SecurityOverviewFromJSON(json: any): SecurityOverview {
    return SecurityOverviewFromJSONTyped(json, false);
}

export function SecurityOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'activeThreats': json['active_threats'],
        'compromisedAccounts': json['compromised_accounts'],
        'failedLogins': json['failed_logins'],
        'resolvedThreats': json['resolved_threats'],
        'securityScore': json['security_score'],
        'suspiciousActivity': json['suspicious_activity'],
        'vulnerabilities': json['vulnerabilities'],
    };
}

export function SecurityOverviewToJSON(json: any): SecurityOverview {
    return SecurityOverviewToJSONTyped(json, false);
}

export function SecurityOverviewToJSONTyped(value?: SecurityOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_threats': value['activeThreats'],
        'compromised_accounts': value['compromisedAccounts'],
        'failed_logins': value['failedLogins'],
        'resolved_threats': value['resolvedThreats'],
        'security_score': value['securityScore'],
        'suspicious_activity': value['suspiciousActivity'],
        'vulnerabilities': value['vulnerabilities'],
    };
}

