/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordRequest
 */
export interface SetPasswordRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SetPasswordRequest
     */
    readonly $schema?: string;
    /**
     * New password
     * @type {string}
     * @memberof SetPasswordRequest
     */
    password: string;
    /**
     * Whether password is temporary and must be changed on next login
     * @type {boolean}
     * @memberof SetPasswordRequest
     */
    temporary: boolean;
}

export function SetPasswordRequestFromJSON(json: any): SetPasswordRequest {
    return SetPasswordRequestFromJSONTyped(json, false);
}

export function SetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '$schema': !exists(json, '$schema') ? undefined : json['$schema'],
        'password': json['password'],
        'temporary': json['temporary'],
    };
}

export function SetPasswordRequestToJSON(value?: SetPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'temporary': value.temporary,
    };
}


