/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface VerificationResponse
 */
export interface VerificationResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof VerificationResponse
     */
    readonly $schema?: string;
    /**
     * Response message
     * @type {string}
     * @memberof VerificationResponse
     */
    message: string;
    /**
     * Whether verification was successful
     * @type {boolean}
     * @memberof VerificationResponse
     */
    success: boolean;
    /**
     * 
     * @type {User}
     * @memberof VerificationResponse
     */
    user?: User;
    /**
     * Whether the item is now verified
     * @type {boolean}
     * @memberof VerificationResponse
     */
    verified: boolean;
}

export function VerificationResponseFromJSON(json: any): VerificationResponse {
    return VerificationResponseFromJSONTyped(json, false);
}

export function VerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '$schema': !exists(json, '$schema') ? undefined : json['$schema'],
        'message': json['message'],
        'success': json['success'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'verified': json['verified'],
    };
}

export function VerificationResponseToJSON(value?: VerificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'success': value.success,
        'user': UserToJSON(value.user),
        'verified': value.verified,
    };
}


