/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Frank Authentication Server
 * A comprehensive authentication server with OAuth2, MFA, Passkeys, SSO, and more
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";

/**
 * Successful login response
 */
export interface LoginResponse {
  /** CSRF token */
  csrf_token: string;
  /** Token expiry timestamp */
  expires_at: number;
  /** Whether MFA is required to complete authentication */
  mfa_required: boolean;
  /** Available MFA methods when MFA is required */
  mfa_types?: string[];
  /** JWTAuth refresh token */
  refresh_token: string;
  /** Session ID */
  session_id?: string;
  /** JWTAuth access token */
  token: string;
  user: User;
}
