/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Frank Authentication Server
 * A comprehensive authentication server with OAuth2, MFA, Passkeys, SSO, and more
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganizationRequestMetadata } from "./updateOrganizationRequestMetadata";

/**
 * Update organization request
 */
export interface UpdateOrganizationRequest {
  /** Whether organization is active */
  active?: boolean;
  /** Organization domain */
  domain?: string;
  /** Organization logo URL */
  logo_url?: string;
  /** Organization metadata */
  metadata?: UpdateOrganizationRequestMetadata;
  /** Organization name */
  name?: string;
  /** Organization plan */
  plan?: string;
}
