// Copyright 2023-present XRaph LLC. All rights reserved.
// This source code is licensed under the XRaph LLC license found
// in the LICENSE file in the root directory of this source tree.
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xraph/frank/ent/organizationprovider"
	"github.com/xraph/frank/ent/predicate"
	"github.com/xraph/frank/ent/providertemplate"
	"github.com/rs/xid"
)

// ProviderTemplateQuery is the builder for querying ProviderTemplate entities.
type ProviderTemplateQuery struct {
	config
	ctx                            *QueryContext
	order                          []providertemplate.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.ProviderTemplate
	withOrganizationProviders      *OrganizationProviderQuery
	modifiers                      []func(*sql.Selector)
	withNamedOrganizationProviders map[string]*OrganizationProviderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderTemplateQuery builder.
func (ptq *ProviderTemplateQuery) Where(ps ...predicate.ProviderTemplate) *ProviderTemplateQuery {
	ptq.predicates = append(ptq.predicates, ps...)
	return ptq
}

// Limit the number of records to be returned by this query.
func (ptq *ProviderTemplateQuery) Limit(limit int) *ProviderTemplateQuery {
	ptq.ctx.Limit = &limit
	return ptq
}

// Offset to start from.
func (ptq *ProviderTemplateQuery) Offset(offset int) *ProviderTemplateQuery {
	ptq.ctx.Offset = &offset
	return ptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ptq *ProviderTemplateQuery) Unique(unique bool) *ProviderTemplateQuery {
	ptq.ctx.Unique = &unique
	return ptq
}

// Order specifies how the records should be ordered.
func (ptq *ProviderTemplateQuery) Order(o ...providertemplate.OrderOption) *ProviderTemplateQuery {
	ptq.order = append(ptq.order, o...)
	return ptq
}

// QueryOrganizationProviders chains the current query on the "organization_providers" edge.
func (ptq *ProviderTemplateQuery) QueryOrganizationProviders() *OrganizationProviderQuery {
	query := (&OrganizationProviderClient{config: ptq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providertemplate.Table, providertemplate.FieldID, selector),
			sqlgraph.To(organizationprovider.Table, organizationprovider.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, providertemplate.OrganizationProvidersTable, providertemplate.OrganizationProvidersColumn),
		)
		fromU = sqlgraph.SetNeighbors(ptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderTemplate entity from the query.
// Returns a *NotFoundError when no ProviderTemplate was found.
func (ptq *ProviderTemplateQuery) First(ctx context.Context) (*ProviderTemplate, error) {
	nodes, err := ptq.Limit(1).All(setContextOp(ctx, ptq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{providertemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) FirstX(ctx context.Context) *ProviderTemplate {
	node, err := ptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProviderTemplate ID from the query.
// Returns a *NotFoundError when no ProviderTemplate ID was found.
func (ptq *ProviderTemplateQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = ptq.Limit(1).IDs(setContextOp(ctx, ptq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{providertemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := ptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProviderTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderTemplate entity is found.
// Returns a *NotFoundError when no ProviderTemplate entities are found.
func (ptq *ProviderTemplateQuery) Only(ctx context.Context) (*ProviderTemplate, error) {
	nodes, err := ptq.Limit(2).All(setContextOp(ctx, ptq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{providertemplate.Label}
	default:
		return nil, &NotSingularError{providertemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) OnlyX(ctx context.Context) *ProviderTemplate {
	node, err := ptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProviderTemplate ID in the query.
// Returns a *NotSingularError when more than one ProviderTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (ptq *ProviderTemplateQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = ptq.Limit(2).IDs(setContextOp(ctx, ptq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{providertemplate.Label}
	default:
		err = &NotSingularError{providertemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := ptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProviderTemplates.
func (ptq *ProviderTemplateQuery) All(ctx context.Context) ([]*ProviderTemplate, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryAll)
	if err := ptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderTemplate, *ProviderTemplateQuery]()
	return withInterceptors[[]*ProviderTemplate](ctx, ptq, qr, ptq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) AllX(ctx context.Context) []*ProviderTemplate {
	nodes, err := ptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProviderTemplate IDs.
func (ptq *ProviderTemplateQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if ptq.ctx.Unique == nil && ptq.path != nil {
		ptq.Unique(true)
	}
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryIDs)
	if err = ptq.Select(providertemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := ptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ptq *ProviderTemplateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryCount)
	if err := ptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ptq, querierCount[*ProviderTemplateQuery](), ptq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) CountX(ctx context.Context) int {
	count, err := ptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ptq *ProviderTemplateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ptq.ctx, ent.OpQueryExist)
	switch _, err := ptq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ptq *ProviderTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := ptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ptq *ProviderTemplateQuery) Clone() *ProviderTemplateQuery {
	if ptq == nil {
		return nil
	}
	return &ProviderTemplateQuery{
		config:                    ptq.config,
		ctx:                       ptq.ctx.Clone(),
		order:                     append([]providertemplate.OrderOption{}, ptq.order...),
		inters:                    append([]Interceptor{}, ptq.inters...),
		predicates:                append([]predicate.ProviderTemplate{}, ptq.predicates...),
		withOrganizationProviders: ptq.withOrganizationProviders.Clone(),
		// clone intermediate query.
		sql:       ptq.sql.Clone(),
		path:      ptq.path,
		modifiers: append([]func(*sql.Selector){}, ptq.modifiers...),
	}
}

// WithOrganizationProviders tells the query-builder to eager-load the nodes that are connected to
// the "organization_providers" edge. The optional arguments are used to configure the query builder of the edge.
func (ptq *ProviderTemplateQuery) WithOrganizationProviders(opts ...func(*OrganizationProviderQuery)) *ProviderTemplateQuery {
	query := (&OrganizationProviderClient{config: ptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ptq.withOrganizationProviders = query
	return ptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderTemplate.Query().
//		GroupBy(providertemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ptq *ProviderTemplateQuery) GroupBy(field string, fields ...string) *ProviderTemplateGroupBy {
	ptq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderTemplateGroupBy{build: ptq}
	grbuild.flds = &ptq.ctx.Fields
	grbuild.label = providertemplate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProviderTemplate.Query().
//		Select(providertemplate.FieldCreatedAt).
//		Scan(ctx, &v)
func (ptq *ProviderTemplateQuery) Select(fields ...string) *ProviderTemplateSelect {
	ptq.ctx.Fields = append(ptq.ctx.Fields, fields...)
	sbuild := &ProviderTemplateSelect{ProviderTemplateQuery: ptq}
	sbuild.label = providertemplate.Label
	sbuild.flds, sbuild.scan = &ptq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderTemplateSelect configured with the given aggregations.
func (ptq *ProviderTemplateQuery) Aggregate(fns ...AggregateFunc) *ProviderTemplateSelect {
	return ptq.Select().Aggregate(fns...)
}

func (ptq *ProviderTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ptq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ptq); err != nil {
				return err
			}
		}
	}
	for _, f := range ptq.ctx.Fields {
		if !providertemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ptq.path != nil {
		prev, err := ptq.path(ctx)
		if err != nil {
			return err
		}
		ptq.sql = prev
	}
	return nil
}

func (ptq *ProviderTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderTemplate, error) {
	var (
		nodes       = []*ProviderTemplate{}
		_spec       = ptq.querySpec()
		loadedTypes = [1]bool{
			ptq.withOrganizationProviders != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderTemplate{config: ptq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ptq.withOrganizationProviders; query != nil {
		if err := ptq.loadOrganizationProviders(ctx, query, nodes,
			func(n *ProviderTemplate) { n.Edges.OrganizationProviders = []*OrganizationProvider{} },
			func(n *ProviderTemplate, e *OrganizationProvider) {
				n.Edges.OrganizationProviders = append(n.Edges.OrganizationProviders, e)
				if !e.Edges.loadedTypes[2] {
					e.Edges.Template = n
				}
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range ptq.withNamedOrganizationProviders {
		if err := ptq.loadOrganizationProviders(ctx, query, nodes,
			func(n *ProviderTemplate) { n.appendNamedOrganizationProviders(name) },
			func(n *ProviderTemplate, e *OrganizationProvider) {
				n.appendNamedOrganizationProviders(name, e)
				if !e.Edges.loadedTypes[2] {
					e.Edges.Template = n
				}
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ptq *ProviderTemplateQuery) loadOrganizationProviders(ctx context.Context, query *OrganizationProviderQuery, nodes []*ProviderTemplate, init func(*ProviderTemplate), assign func(*ProviderTemplate, *OrganizationProvider)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*ProviderTemplate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(organizationprovider.FieldTemplateID)
	}
	query.Where(predicate.OrganizationProvider(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(providertemplate.OrganizationProvidersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TemplateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "template_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ptq *ProviderTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ptq.querySpec()
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	_spec.Node.Columns = ptq.ctx.Fields
	if len(ptq.ctx.Fields) > 0 {
		_spec.Unique = ptq.ctx.Unique != nil && *ptq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ptq.driver, _spec)
}

func (ptq *ProviderTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(providertemplate.Table, providertemplate.Columns, sqlgraph.NewFieldSpec(providertemplate.FieldID, field.TypeString))
	_spec.From = ptq.sql
	if unique := ptq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ptq.path != nil {
		_spec.Unique = true
	}
	if fields := ptq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providertemplate.FieldID)
		for i := range fields {
			if fields[i] != providertemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ptq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ptq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ptq *ProviderTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ptq.driver.Dialect())
	t1 := builder.Table(providertemplate.Table)
	columns := ptq.ctx.Fields
	if len(columns) == 0 {
		columns = providertemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ptq.sql != nil {
		selector = ptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ptq.ctx.Unique != nil && *ptq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ptq.modifiers {
		m(selector)
	}
	for _, p := range ptq.predicates {
		p(selector)
	}
	for _, p := range ptq.order {
		p(selector)
	}
	if offset := ptq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ptq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ptq *ProviderTemplateQuery) ForUpdate(opts ...sql.LockOption) *ProviderTemplateQuery {
	if ptq.driver.Dialect() == dialect.Postgres {
		ptq.Unique(false)
	}
	ptq.modifiers = append(ptq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ptq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ptq *ProviderTemplateQuery) ForShare(opts ...sql.LockOption) *ProviderTemplateQuery {
	if ptq.driver.Dialect() == dialect.Postgres {
		ptq.Unique(false)
	}
	ptq.modifiers = append(ptq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ptq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ptq *ProviderTemplateQuery) Modify(modifiers ...func(s *sql.Selector)) *ProviderTemplateSelect {
	ptq.modifiers = append(ptq.modifiers, modifiers...)
	return ptq.Select()
}

// WithNamedOrganizationProviders tells the query-builder to eager-load the nodes that are connected to the "organization_providers"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (ptq *ProviderTemplateQuery) WithNamedOrganizationProviders(name string, opts ...func(*OrganizationProviderQuery)) *ProviderTemplateQuery {
	query := (&OrganizationProviderClient{config: ptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if ptq.withNamedOrganizationProviders == nil {
		ptq.withNamedOrganizationProviders = make(map[string]*OrganizationProviderQuery)
	}
	ptq.withNamedOrganizationProviders[name] = query
	return ptq
}

// ProviderTemplateGroupBy is the group-by builder for ProviderTemplate entities.
type ProviderTemplateGroupBy struct {
	selector
	build *ProviderTemplateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ptgb *ProviderTemplateGroupBy) Aggregate(fns ...AggregateFunc) *ProviderTemplateGroupBy {
	ptgb.fns = append(ptgb.fns, fns...)
	return ptgb
}

// Scan applies the selector query and scans the result into the given value.
func (ptgb *ProviderTemplateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ptgb.build.ctx, ent.OpQueryGroupBy)
	if err := ptgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderTemplateQuery, *ProviderTemplateGroupBy](ctx, ptgb.build, ptgb, ptgb.build.inters, v)
}

func (ptgb *ProviderTemplateGroupBy) sqlScan(ctx context.Context, root *ProviderTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ptgb.fns))
	for _, fn := range ptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ptgb.flds)+len(ptgb.fns))
		for _, f := range *ptgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ptgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ptgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderTemplateSelect is the builder for selecting fields of ProviderTemplate entities.
type ProviderTemplateSelect struct {
	*ProviderTemplateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pts *ProviderTemplateSelect) Aggregate(fns ...AggregateFunc) *ProviderTemplateSelect {
	pts.fns = append(pts.fns, fns...)
	return pts
}

// Scan applies the selector query and scans the result into the given value.
func (pts *ProviderTemplateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pts.ctx, ent.OpQuerySelect)
	if err := pts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderTemplateQuery, *ProviderTemplateSelect](ctx, pts.ProviderTemplateQuery, pts, pts.inters, v)
}

func (pts *ProviderTemplateSelect) sqlScan(ctx context.Context, root *ProviderTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pts.fns))
	for _, fn := range pts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pts *ProviderTemplateSelect) Modify(modifiers ...func(s *sql.Selector)) *ProviderTemplateSelect {
	pts.modifiers = append(pts.modifiers, modifiers...)
	return pts
}
